const books = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    price: 1499,
    originalPrice: 1999,
    rating: 4.8,
    reviews: 2847,
    category: "Self-Help",
    format: "Paperback",
    isbn: "9780735211292",
    badge: "Bestseller",
    stock: "In Stock",
  },
  {
    id: 2,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 1299,
    originalPrice: 1699,
    rating: 4.7,
    reviews: 1923,
    category: "Finance",
    format: "Paperback",
    isbn: "9780857197689",
    badge: null,
    stock: "In Stock",
  },
  {
    id: 3,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: 1199,
    originalPrice: null,
    rating: 4.6,
    reviews: 4532,
    category: "Finance",
    format: "Paperback",
    isbn: "9781612680194",
    badge: "Classic",
    stock: "In Stock",
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    price: 1399,
    originalPrice: null,
    rating: 4.6,
    reviews: 1240,
    category: "Productivity",
    format: "Hardcover",
    isbn: "9781455586691",
    badge: null,
    stock: "Only 3 left",
  },
  {
    id: 5,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 1899,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 3102,
    category: "Psychology",
    format: "Paperback",
    isbn: "9780374533557",
    badge: "Award Winner",
    stock: "In Stock",
  },
  {
    id: 6,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 1599,
    originalPrice: 2099,
    rating: 4.8,
    reviews: 5621,
    category: "History",
    format: "Paperback",
    isbn: "9780062316097",
    badge: "Top Rated",
    stock: "In Stock",
  },
  {
    id: 7,
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    price: 1799,
    originalPrice: null,
    rating: 4.6,
    reviews: 3890,
    category: "Philosophy",
    format: "Hardcover",
    isbn: "9780140280197",
    badge: null,
    stock: "In Stock",
  },
  {
    id: 8,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 1099,
    originalPrice: 1399,
    rating: 4.7,
    reviews: 6781,
    category: "Fiction",
    format: "Paperback",
    isbn: "9780062315007",
    badge: "Staff Pick",
    stock: "In Stock",
  },
  {
    id: 9,
    title: "Becoming",
    author: "Michelle Obama",
    price: 1699,
    originalPrice: null,
    rating: 4.9,
    reviews: 4210,
    category: "Biography",
    format: "Hardcover",
    isbn: "9781524763138",
    badge: null,
    stock: "In Stock",
  },
  {
    id: 10,
    title: "Educated",
    author: "Tara Westover",
    price: 1450,
    originalPrice: 1850,
    rating: 4.8,
    reviews: 2156,
    category: "Biography",
    format: "Paperback",
    isbn: "9780399590504",
    badge: null,
    stock: "In Stock",
  },
  {
    id: 11,
    title: "Can't Hurt Me",
    author: "David Goggins",
    price: 1550,
    originalPrice: null,
    rating: 4.8,
    reviews: 3421,
    category: "Self-Help",
    format: "Hardcover",
    isbn: "9781544512273",
    badge: "Trending",
    stock: "In Stock",
  },
  {
    id: 12,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 1250,
    originalPrice: 1599,
    rating: 4.5,
    reviews: 2890,
    category: "Self-Help",
    format: "Paperback",
    isbn: "9780062457714",
    badge: null,
    stock: "In Stock",
  },
];

export default books;