const books = [
  {
    id: 1,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    price: 1200,
    rating: 4.8,
    category: "Business",
    description: "What the rich teach their kids about money that the poor do not.",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
    badge: "Bestseller",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    price: 1500,
    rating: 4.9,
    category: "Self-Help",
    description: "Tiny changes, remarkable results. Build good habits and break bad ones.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    badge: "Trending",
  },
  {
    id: 3,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 1800,
    rating: 4.7,
    category: "Finance",
    description: "Timeless lessons on wealth, greed, and happiness.",
    image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=80",
    badge: null,
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    price: 1400,
    rating: 4.6,
    category: "Productivity",
    description: "Rules for focused success in a distracted world.",
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    badge: "Staff Pick",
  },
  {
    id: 5,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 1350,
    rating: 4.5,
    category: "Fiction",
    description: "Between life and death there is a library with infinite possibilities.",
    image: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80",
    badge: "New",
  },
  {
    id: 6,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 1900,
    rating: 4.7,
    category: "Psychology",
    description: "The two systems that drive the way we think.",
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
    badge: null,
  },
  {
    id: 7,
    title: "Zero to One",
    author: "Peter Thiel",
    price: 1600,
    rating: 4.6,
    category: "Business",
    description: "Notes on startups, or how to build the future.",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df4?auto=format&fit=crop&w=600&q=80",
    badge: "Classic",
  },
  {
    id: 8,
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 1750,
    rating: 4.9,
    category: "Sci-Fi",
    description: "A lone astronaut must save the earth from disaster.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    badge: "Award Winner",
  },
];

export default books;