const books = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    price: 1499,
    originalPrice: 1999,
    rating: 4.8,
    reviews: 2847,
    category: "Self-Help",
    format: "Paperback",
    isbn: "9780735211292",
    badge: "Bestseller",
    stock: "In Stock",
    cover: { bg: "#1a1a2e", accent: "#e94560", pattern: "dots" },
    description: "No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviours that lead to remarkable results.",
    pages: 320,
    publisher: "Avery",
    year: 2018,
    tags: ["Habits", "Productivity", "Self-Improvement"],
  },
  {
    id: 2,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 1299,
    originalPrice: 1699,
    rating: 4.7,
    reviews: 1923,
    category: "Finance",
    format: "Paperback",
    isbn: "9780857197689",
    badge: null,
    stock: "In Stock",
    cover: { bg: "#0f3460", accent: "#f5a623", pattern: "lines" },
    description: "Timeless lessons on wealth, greed, and happiness. Doing well with money isn't necessarily about what you know. It's about how you behave. And behaviour is hard to teach, even to really smart people.",
    pages: 256,
    publisher: "Harriman House",
    year: 2020,
    tags: ["Finance", "Investing", "Mindset"],
  },
  {
    id: 3,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: 1199,
    originalPrice: null,
    rating: 4.6,
    reviews: 4532,
    category: "Finance",
    format: "Paperback",
    isbn: "9781612680194",
    badge: "Classic",
    stock: "In Stock",
    cover: { bg: "#7b2d00", accent: "#f7c948", pattern: "diagonal" },
    description: "Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend — and the ways in which both men shaped his thoughts about money and investing.",
    pages: 336,
    publisher: "Plata Publishing",
    year: 1997,
    tags: ["Finance", "Wealth", "Real Estate"],
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    price: 1399,
    originalPrice: null,
    rating: 4.6,
    reviews: 1240,
    category: "Productivity",
    format: "Hardcover",
    isbn: "9781455586691",
    badge: null,
    stock: "Only 3 left",
    cover: { bg: "#1b1b2f", accent: "#c84b31", pattern: "grid" },
    description: "Deep work is the ability to focus without distraction on a cognitively demanding task. In this book, Cal Newport makes the case that this skill is becoming increasingly rare and valuable in our economy.",
    pages: 304,
    publisher: "Grand Central",
    year: 2016,
    tags: ["Focus", "Productivity", "Career"],
  },
  {
    id: 5,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 1899,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 3102,
    category: "Psychology",
    format: "Paperback",
    isbn: "9780374533557",
    badge: "Award Winner",
    stock: "In Stock",
    cover: { bg: "#2d4a22", accent: "#f0c040", pattern: "circles" },
    description: "In this international bestseller, Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think — and how they shape our judgements and decisions.",
    pages: 499,
    publisher: "Farrar, Straus and Giroux",
    year: 2011,
    tags: ["Psychology", "Decision-Making", "Behavioural Economics"],
  },
  {
    id: 6,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 1599,
    originalPrice: 2099,
    rating: 4.8,
    reviews: 5621,
    category: "History",
    format: "Paperback",
    isbn: "9780062316097",
    badge: "Top Rated",
    stock: "In Stock",
    cover: { bg: "#2c1810", accent: "#e8a020", pattern: "dots" },
    description: "A brief history of humankind. One hundred thousand years ago, at least six human species inhabited the earth. Today there is just one. How did our species succeed in the battle for dominance?",
    pages: 443,
    publisher: "Harper",
    year: 2011,
    tags: ["History", "Anthropology", "Evolution"],
  },
  {
    id: 7,
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    price: 1799,
    originalPrice: null,
    rating: 4.6,
    reviews: 3890,
    category: "Philosophy",
    format: "Hardcover",
    isbn: "9780140280197",
    badge: null,
    stock: "In Stock",
    cover: { bg: "#0d0d0d", accent: "#c0392b", pattern: "lines" },
    description: "In the book that should be read by anyone who wants to understand the world, Robert Greene distils 3,000 years of the history of power into 48 essential laws.",
    pages: 480,
    publisher: "Viking",
    year: 1998,
    tags: ["Power", "Strategy", "History"],
  },
  {
    id: 8,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 1099,
    originalPrice: 1399,
    rating: 4.7,
    reviews: 6781,
    category: "Fiction",
    format: "Paperback",
    isbn: "9780062315007",
    badge: "Staff Pick",
    stock: "In Stock",
    cover: { bg: "#1a3a4a", accent: "#f39c12", pattern: "diagonal" },
    description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His journey teaches us about the essential wisdom of listening to our hearts.",
    pages: 208,
    publisher: "HarperOne",
    year: 1988,
    tags: ["Fiction", "Adventure", "Spirituality"],
  },
  {
    id: 9,
    title: "Becoming",
    author: "Michelle Obama",
    price: 1699,
    originalPrice: null,
    rating: 4.9,
    reviews: 4210,
    category: "Biography",
    format: "Hardcover",
    isbn: "9781524763138",
    badge: null,
    stock: "In Stock",
    cover: { bg: "#1c3a5e", accent: "#27ae60", pattern: "circles" },
    description: "In her memoir, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her — from her childhood on the South Side of Chicago to the years she spent at the world's most famous address.",
    pages: 448,
    publisher: "Crown",
    year: 2018,
    tags: ["Memoir", "Politics", "Inspiration"],
  },
  {
    id: 10,
    title: "Educated",
    author: "Tara Westover",
    price: 1450,
    originalPrice: 1850,
    rating: 4.8,
    reviews: 2156,
    category: "Biography",
    format: "Paperback",
    isbn: "9780399590504",
    badge: null,
    stock: "In Stock",
    cover: { bg: "#2e4057", accent: "#e74c3c", pattern: "grid" },
    description: "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University. A story about the power of education to open minds and change lives.",
    pages: 352,
    publisher: "Random House",
    year: 2018,
    tags: ["Memoir", "Education", "Family"],
  },
  {
    id: 11,
    title: "Can't Hurt Me",
    author: "David Goggins",
    price: 1550,
    originalPrice: null,
    rating: 4.8,
    reviews: 3421,
    category: "Self-Help",
    format: "Hardcover",
    isbn: "9781544512273",
    badge: "Trending",
    stock: "In Stock",
    cover: { bg: "#111111", accent: "#e67e22", pattern: "lines" },
    description: "Master your mind and defy the odds. For David Goggins, childhood was a nightmare — poverty, prejudice, and physical abuse colored his days and haunted his nights. Learn how he became one of the world's top endurance athletes.",
    pages: 364,
    publisher: "Lioncrest",
    year: 2018,
    tags: ["Mindset", "Fitness", "Resilience"],
  },
  {
    id: 12,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 1250,
    originalPrice: 1599,
    rating: 4.5,
    reviews: 2890,
    category: "Self-Help",
    format: "Paperback",
    isbn: "9780062457714",
    badge: null,
    stock: "In Stock",
    cover: { bg: "#e74c3c", accent: "#f1c40f", pattern: "dots" },
    description: "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be positive all the time so we can truly become better, happier people.",
    pages: 224,
    publisher: "HarperOne",
    year: 2016,
    tags: ["Mindset", "Self-Help", "Philosophy"],
  },
];

export default books;